@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_TOP_DOWN

title Proof of Visit Dapp

Person(person, "AppUser", "A User who uses the appliaction.")

System_Boundary(client_app, "Sample System") {
    System(app, "Client App", "An android application.")
    Container(web3j, "Web3j Framework", "Web3j", "A Web3j Framework.")
}

Container(smart_contract, "SmartContract", "Solidity 0.5.0", "A SmartContract deployed on Bloxberg.")
System(server, "Java Server")

Rel(person, client_app, "uses")
Rel(app, web3j, "implements")
Rel(client_app, server, "ask server to transfer tokens")
Rel(server, smart_contract, "transfer tokens")
Rel(client_app, smart_contract, "show tokens")
@enduml